### ISSUE TITLE
npm audit reports security issues

### ISSUE THREAD

**Issue by obvious-burner** [SmartieCodes/timewarp#1]
```
/home/[redacted]/Desktop/timewarp$ npm audit

                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Moderate        Cross-Site Scripting

  Package         materialize-css

  Patched in      No patch available

  Dependency of   materialize-css [dev]

  Path            materialize-css

  More info       https://npmjs.com/advisories/817


  Moderate        Cross-Site Scripting

  Package         materialize-css

  Patched in      No patch available

  Dependency of   materialize-css [dev]

  Path            materialize-css

  More info       https://npmjs.com/advisories/818

found 2 moderate severity vulnerabilities in 363 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
```  
According to the npm advisory, these two issues have been sitting unpatched since April 2019. Additionally, the MaterializeCSS module also seems to be unmaintained. (last publish was from around a year ago) Perhaps it would be a good idea to replace it with something else? I'll try looking for alternatives. (original issue: Dogfalo/materialize#6286)

**Comment by AutumnRivers** [comment]
Materialize itself isn't maintained anymore afaik as well. The only other option would be downloading from the Materialize website, but that's just as updated as the module. Finally, Timewarp does not use the affected components, so cast your worries aside. Will be closing this. If anyone else has concerns, feel free to contact me.
